# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 秦观园
subtitle: 程序猿，农民的儿子，山上下来的土根儿
description: Q 的博客 | java
author: Q
language: zh-CN
timezone: Asia/Chongqing

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://qzztf.com
root: /
permalink:  post/:abbrlink/
abbrlink:
  alg: crc16  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
# 使用crc16已经能生成65535篇文章了，对于个人博客感觉已经够用了
# 使用hex是因为我觉得带字母好看一点
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  # prependRoot: true
  # postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: 未分类
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#plugins: hexo-qiniu-sync
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/qinzaizhen/qinzaizhen.github.io.git
  branch: master

# qiniu:
#   offline: false
#   sync: true
#   bucket: blog
#   #secret_file: sec/qn.json or C:
#   access_key: d_r5OCgrqW_CpzO779_Grec44nXfNK-C5spKatzt
#   secret_key: IBLhmsKWk4EbhIkg12LLVmbjKZSdf_f99Plocv8_
#   dirPrefix: 
#   urlPrefix: http://ooll8xqpq.bkt.clouddn.com
#   up_host: http://upload.qiniu.com
#   local_dir: static
#   update_exist: true
#   image: 
#     folder: images
#     extend: 
#   js:
#     folder: js
#   css:
#     folder: css

# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760 # 缓存的最大文件大小，以字节为单位
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
  # 静态文件合集，如果你的站点使用了例如webp格式的文件，请将文件类型添加进去。
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /* # 如果你需要加载CDN资源，请配置该选项，如果没有，可以不配置。
      handler: cacheFirst
      options:
        origin: http://qzztf.com # 可替换成你的 url
